---
repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=.bandit.yaml
        files: ^custom_components/.+\.py$
  - repo: https://github.com/python/black
    rev: 21.7b0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        language_version: python3
        files: ^(custom_components/.+)?[^/]+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.json"
          - --quiet-level=4
          - --ignore-words=ignore-spelling-words.txt
        exclude_types: [json]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.5.0
          - pydocstyle==5.0.1
        args:
          - --ignore=E501,W503,F401
        files: ^custom_components/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        args:
          - --diff
        files: ^(custom_components/keyatome/)[^/]+.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        files: ^custom_components/.+\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-json
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
        files: ^(custom_components/.+)?[^/]+\.py$
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: shellcheck
        files: ^script/.+
