---
name: CI

on:
  pull_request:
    branches:
      - dev
      - master

  push:
    branches:
      - dev
      - master

jobs:

  lint:

    name: "Linting & Static Analysis"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: x64

      - uses: pre-commit/action@v2.0.3
        env:
          SKIP: no-commit-to-branch
